// Comprehensive Mock Data for Kanoon Mitra

export const MOCK_LAWYERS = [
  {
    id: "lawyer-1",
    name: "Adv. Rajesh Sharma",
    experience: "15+ Years",
    rating: 4.9,
    reviewsCount: 142,
    specializations: ["Criminal Law", "FIR & Bail", "Cyber Crime"],
    location: "New Delhi",
    languages: ["Hindi", "English"],
    fee: "₹1,500 / slot",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
    barCouncilId: "D/1024/2009",
    availability: "Mon - Sat (10:00 AM - 6:00 PM)",
    bio: "Senior Advocate at Delhi High Court specializing in criminal defense, FIR quashing, and cyber crime litigations.",
  },
  {
    id: "lawyer-2",
    name: "Adv. Priya Ananth",
    experience: "12+ Years",
    rating: 4.8,
    reviewsCount: 98,
    specializations: ["Family & Property Law", "Divorce & Custody", "Civil Disputes"],
    location: "Bengaluru",
    languages: ["English", "Hindi", "Kannada"],
    fee: "₹1,200 / slot",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    barCouncilId: "KAR/892/2012",
    availability: "Mon - Fri (11:00 AM - 7:00 PM)",
    bio: "Specialist in family mediation, property partition suits, and consumer rights protection.",
  },
  {
    id: "lawyer-3",
    name: "Adv. Vikramjit Singh",
    experience: "18+ Years",
    rating: 4.95,
    reviewsCount: 210,
    specializations: ["Corporate & Contract Law", "RTI & Constitutional Rights", "Real Estate"],
    location: "Mumbai",
    languages: ["English", "Hindi", "Marathi"],
    fee: "₹2,000 / slot",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80",
    barCouncilId: "MAH/451/2006",
    availability: "Mon - Sat (9:30 AM - 5:30 PM)",
    bio: "Corporate legal consultant, RTI activist, and High Court practitioner with expertise in business agreements and property verification.",
  },
  {
    id: "lawyer-4",
    name: "Adv. Sunita Roy",
    experience: "9+ Years",
    rating: 4.7,
    reviewsCount: 76,
    specializations: ["Cyber Crime", "Online Fraud", "Intellectual Property"],
    location: "Kolkata",
    languages: ["Hindi", "English", "Bengali"],
    fee: "₹1,000 / slot",
    image: "https://images.unsplash.com/photo-1580894732413-a70d8a97323c?w=400&auto=format&fit=crop&q=80",
    barCouncilId: "WB/774/2015",
    availability: "Tue - Sun (10:00 AM - 6:00 PM)",
    bio: "Certified Cyber Law Specialist helping victims of financial cyber fraud, data theft, and online harassment.",
  },
];

export const MOCK_LEGAL_DOCS = [
  {
    id: "doc-rent-agreement",
    title: "Residential House Rent Agreement",
    category: "Property & Rental",
    description: "Legally valid rent agreement draft for tenants and landlords with standard clauses for rent, security deposit, and lock-in period.",
    icon: "🏠",
    fields: ["landlordName", "tenantName", "propertyAddress", "monthlyRent", "depositAmount", "agreementTerm"],
  },
  {
    id: "doc-nda",
    title: "Non-Disclosure Agreement (NDA)",
    category: "Corporate & Business",
    description: "Confidentiality agreement to protect sensitive business ideas, trade secrets, and proprietary information.",
    icon: "🔒",
    fields: ["disclosingParty", "receivingParty", "purpose", "termYears", "governingState"],
  },
  {
    id: "doc-affidavit",
    title: "General Purpose Affidavit",
    category: "General Legal",
    description: "Sworn written statement used as official evidence for name change, address proof, or lost documents declaration.",
    icon: "📜",
    fields: ["deponentName", "fatherName", "residenceAddress", "declarationText", "purposeText"],
  },
  {
    id: "doc-poa",
    title: "General Power of Attorney (POA)",
    category: "Property & Financial",
    description: "Legal document granting authority to an attorney-in-fact to act on behalf of the principal in property or financial matters.",
    icon: "🖋️",
    fields: ["principalName", "attorneyName", "scopeOfPower", "effectiveDate"],
  },
];

export const MOCK_BNS_SECTIONS = [
  {
    bnsCode: "BNS Section 103 (IPC 302)",
    title: "Punishment for Murder",
    category: "Criminal Law",
    summary: "Deals with punishment for murder, establishing death penalty or imprisonment for life along with monetary fine.",
  },
  {
    bnsCode: "BNS Section 318 (IPC 420)",
    title: "Cheating and Dishonestly Inducing Delivery of Property",
    category: "Financial Fraud",
    summary: "Applies to financial scams, fraudulent promises, and deceptive property transfers. Imprisonment up to 7 years.",
  },
  {
    bnsCode: "BNS Section 308 (IPC 384)",
    title: "Extortion and Blackmail",
    category: "Criminal Intimidation",
    summary: "Intentionally putting any person in fear of injury to demand money, digital ransom, or property.",
  },
  {
    bnsCode: "BNS Section 74 (IPC 354)",
    title: "Assault or Criminal Force to Woman with Intent to Outrage Modesty",
    category: "Women Protection",
    summary: "Protects women against harassment, stalking, and criminal force. Non-bailable offense.",
  },
];

export const MOCK_RTI_DEPARTMENTS = [
  { id: "dept-muncipal", name: "Municipal Corporation / Local Urban Body", area: "Roads, Sanitation, Building Permits, Water Supply" },
  { id: "dept-police", name: "State Police Department & Crime Records", area: "FIR Status, Investigation Updates, Passport Verification" },
  { id: "dept-revenue", name: "Revenue & Land Record Department", area: "Property mutation, Tehsil records, Land titles" },
  { id: "dept-education", name: "State Education Board & Universities", area: "Answer key evaluation, Scholarship funds, Faculty recruitment" },
  { id: "dept-transport", name: "Regional Transport Office (RTO)", area: "Driving license delays, Vehicle registration details" },
];
